config/routes.rb
Pixtr::Application.routes.draw do
get "galleries/random_gallery" => "random_galleries#show"

  root "homes#show"

get "/search" => "searches#index"
  resource :search, only: [:index]

  resource :dashboard, only: [:show]

  resources :tags, only: [:show]
  
  resources :galleries do
    member do  #
      post "like" => "gallery_likes#create"   #should have just called it "likes"
      delete "unlike" => "gallery_likes#destroy"
    end
    resources :images, only: [:new, :create]
  end

  resources :groups, only: [:index, :new, :create, :show] do
    member do
      post "join" => "group_memberships#create"
      delete "leave" => "group_memberships#destroy"
    end
    member do  #
      post "like" => "group_likes#create"   #should have just called it "likes"
      delete "unlike" => "group_likes#destroy"
    end
  end

  resources :images, except: [:index, :new, :create] do
    member do  #
      post "like" => "image_likes#create"   #should have just called it "likes"
      delete "unlike" => "image_likes#destroy"
    end
    resources :comments, only: [:create]
  end

  resources :comments, only: [:destroy]

  resources :users, only: [:show] do
    member do # /users/:id.  A member of the user.
      post "follow" => "following_relationships#create"
      delete "unfollow" => "following_relationships#destroy"
    end
  end

  resources :charges, only: [:new, :create]


end

app/models/group.rb
class Group < ActiveRecord::Base
  has_many :group_memberships, dependent: :destroy
  has_many :members, through: :group_memberships

  has_many :group_images, dependent: :destroy
  has_many :images, through: :group_images

  has_many :joining_group_activities, as: :subject, dependent: :destroy

  has_many :likes, as: :likable, dependent: :destroy

  validates :name, presence: true
  # validates :user_id, presence: true, uniqueness: { scope: :likable}
  # validates :likable, presence: true

  # def has_member(user)
  #   member_ids.includes? user.user_id
  # end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :authorize, except: [:show]

  def index
    @groups = current_user.groups
  end

  def new 
    @group = Group.new
  end

  def create 
    @group = Group.new(group_params)
    if @group.save
      current_user.join @group
      redirect_to @group
    else
      render :new
    end
  end

  def show
    @group = Group.find(params[:id])
    @images = @group.images.includes(gallery: [:user])
  end

private

  def group_params
    params.require(:group).permit(
      :name,
      :description
      )
  end
end

app/views/groups/_join_group_button.html.erb
<% if current_user.member? group %>
  <%= button_to "Leave Group", leave_group_path(group), method: :delete, remote: true %>
<% else %>
  <%= button_to "Join Group", join_group_path(group), remote: true %>
<% end %>

app/views/groups/_like_button_form.html.erb
<% if current_user.likes? group %>
    <%= button_to "Unlike Group", unlike_group_path(group), method: :delete, remote: true %>
<% else %>  
    <%= button_to "Like Group", like_group_path(group), remote: true %>
<% end %>

<%= pluralize(group.likes.count, "Like") %>

app/views/groups/index.html.erb
<h2>My Groups</h2>

<%= link_to "Add a Group", new_group_path %>

<ul>
  <% @groups.each do |group| %>
    <li><%= link_to group.name, group %></li>
  <% end %>
<ul>

app/views/groups/new.html.erb
<%= form_for @group do |form| %>

<%= render "form_errors", target: @group %>

  <div>
    <%=form.text_field :name, placeholder: "Name" %>
  </div>
  <div>
    <%=form.text_field :description, placeholder: "Description" %>
  </div>
  <%= form.submit "Create Group" %>
<% end %> 

app/views/groups/show.html.erb
<h2><%= @group.name %></h2>

<% if signed_in? %>
  <div id="join_group_button">
    <%= render "join_group_button", group: @group %>
  </div>
<% end %>

<% if signed_in? %>
  <div id="like_button_form" %>
    <%= render "like_button_form", group: @group %>
  </div>

<% end %>

<%= render @images %>