config/routes.rb
Pixtr::Application.routes.draw do
get "galleries/random_gallery" => "random_galleries#show"

  root "homes#show"

get "/search" => "searches#index"
  resource :search, only: [:index]

  resource :dashboard, only: [:show]

  resources :tags, only: [:show]
  
  resources :galleries do
    member do  #
      post "like" => "gallery_likes#create"   #should have just called it "likes"
      delete "unlike" => "gallery_likes#destroy"
    end
    resources :images, only: [:new, :create]
  end

  resources :groups, only: [:index, :new, :create, :show] do
    member do
      post "join" => "group_memberships#create"
      delete "leave" => "group_memberships#destroy"
    end
    member do  #
      post "like" => "group_likes#create"   #should have just called it "likes"
      delete "unlike" => "group_likes#destroy"
    end
  end

  resources :images, except: [:index, :new, :create] do
    member do  #
      post "like" => "image_likes#create"   #should have just called it "likes"
      delete "unlike" => "image_likes#destroy"
    end
    resources :comments, only: [:create]
  end

  resources :comments, only: [:destroy]

  resources :users, only: [:show] do
    member do # /users/:id.  A member of the user.
      post "follow" => "following_relationships#create"
      delete "unfollow" => "following_relationships#destroy"
    end
  end

  resources :charges, only: [:new, :create]


end

app/models/image.rb
class Image < ActiveRecord::Base
  belongs_to :gallery
  has_many :comments, dependent: :destroy

  has_many :group_images, dependent: :destroy
  has_many :groups, through: :group_images

  has_many :likes, as: :likable, dependent: :destroy

  has_many :user_likes, 
    through: :likes, source: :user

  has_many :taggings
  has_many :tags, through: :taggings

  validates :name, presence: true
  validates :description, presence: true
  validates :url, presence: true

  # validates :name, :description, :url, presenbce: true  ##same as the above just different syntax

  def user
    gallery.user
  end

  def self.tagged_with(name)
    Tag.find_by_name!(name).images
  end

  def self.tag_counts
    Tag.select("tags.*, count(taggings.tag_id) as count").
    joins(:taggings).group("taggings.tag_id")
  end
 
  def tag_list
    tags.pluck(:name).join(", ")  #calls method :name on all tags and returns array of those names, separated by commas
  end

  def tag_list=(tag_string)
    self.tags = Tag.from_tag_list(tag_string)
  end

  # def self.search(search_params)
  #   query = search_params[:query]
  #   tags = Tag.search(search_params)
  #   image_ids = Tagging.where(tag_id: tags).pluck(:image_id)
  #   where("name ILIKE :query OR description ILIKE :query OR id IN (:image_ids)", query: "%#{query}%", image_ids: image_ids)
  # end

  # def self.search(query)
  #   where("name ilike ? OR description ilike ?", "%#{query}%", "%#{query}%") 
  # end
  
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController

  def index
    if params[:tag]
      @images = Image.tagged_with(params[:tag])
    else
      @images = current_user.images
    end 

    if params[:search]
      @users = User.search(params[:search]).order("created_at DESC")
    else
      @users = User.all.order('created_at DESC')
    end
  end

  def new
    @gallery = current_user.galleries.find(params[:gallery_id])
    @image = Image.new
  end

  def create
    @gallery = current_user.galleries.find(params[:gallery_id])
    @image = @gallery.images.new(image_params)

    if @image.save
      current_user.notify_followers(@image, @image, "ImageActivity")
      redirect_to @gallery
    else
      render :new #only renders the template and displays the previously entered data o user can make changes
    end
  end

  def show
    @image = Image.find(params[:id])
    @comment = Comment.new
    @comments = @image.comments.newest.page(params[:page]).per(3).includes(:user)
    @tags = @image.tags
  end

  def edit
    @image = current_user.images.find(params[:id])
    @groups = current_user.groups
  end

  def update 
    @image = current_user.images.find(params[:id])
    
    if @image.update(image_params)
      redirect_to @image
    else
      @groups = current_user.groups
      render :edit
    end
  end

  def destroy
    image = current_user.images.find(params[:id])
    image.destroy
    redirect_to image.gallery
  end

 #VVV same as above before image was changed in model
  # def destroy
  #   image = Image.find(params[:id])
  #   image.destroy
  #   redirect_to gallery_path(image.gallery_id)
  # end

private

  def image_params
    params.require(:image).permit(
      :name, 
      :url, 
      :description,
      :tag_list,
      group_ids: []
    )
  end

end

app/views/images/_image.html.erb
<%= link_to image_tag(image.url, width: 400), image %>
by: <%= link_to image.user.email, image.user %>

app/views/images/_like_button_form.html.erb
<% if current_user.likes? image %>
  <%= button_to "Unlike Image", unlike_image_path(image), method: :delete, remote: true %>
<% else %>  
  <%= button_to "Like Image", like_image_path(image), remote: true %>
<% end %>

<%= pluralize(image.likes.count, "Like") %>

app/views/images/edit.html.erb
<%= form_for(@image) do |form| %>

<%= render "form_errors", target: @image %>

<div>
  <%= form.label "Name" %>
  <%= form.text_field :name %>
</div>
<div>
  <%= form.label "URL" %>
  <%= form.text_field :url %>
</div>
<div>
  <%= form.label "Description" %>
  <%= form.text_field :description %>
</div>
<div class="field">
  <%= form.label :tag_list, "Tags (separated by commas)" %><br />
  <%= form.text_field :tag_list %>
</div>
<div>
  <%= form.collection_check_boxes :group_ids, @groups, :id, :name %> 

</div>
  <%= form.submit "Update Image" %>

<% end %>

app/views/images/index.html.erb
<% @images.each do |image| %>
  <div>
    <%= link_to @image.name. @image %>
  </div>
<% end %>

app/views/images/new.html.erb
<h2>New Image </h2>


<%= form_for [@gallery, @image] do |form| %>
  <%= render "form_errors", target: @image %>

  <div>
    <%= form.text_field :name, placeholder: "Name" %>
  </div>
  <div>
    <%= form.text_field :description, placeholder: "Description" %>
  </div>
  <div>
  <div>
    <%= form.text_field :url, placeholder: "URL" %>
  </div>
  <div>
  <%= form.submit "Create image" %>
<% end %>

app/views/images/show.html.erb
<h2><%= @image.name %></h2>

<% if @image.user == current_user %>
  <div>
    <%= link_to "Edit", edit_image_path(@image) %>

    <%= link_to "Delete", @image, 
      method: :delete, 
      confirm: "Are you sure you want to delete this image?" %>
  </div>
<% end %>

<%= image_tag(@image.url, width: 500) %>
<h2><%= @image.description %></h2>
<p> Tags: <% @tags.each do |tag| %>
  <%= link_to tag.name, tag %>
<% end %></p>
<p>Added by: <%= link_to @image.user.email, @image.user %></p>
<p>Added on: <%= @image.created_at.to_date %></p>

<% if signed_in? %>

  <div id="like_button_form">
    <%= render "like_button_form", image: @image %>
  </div>

  <%= form_for [@image, @comment], remote: true do |form| %>
    <%= form.text_area :body %>
    <%= form.submit "Comment" %>
  <% end %> 

<% else %>
  <%= link_to "Sign In", sign_in_path %> to comment
<% end %>

<div id="comments">
  <%= render @comments %>
  <% # render can render a collection.  It iterates over each of the things in the collection %>
  <% # Ruby knows the class of the object, here comment, and it uses a local variable of the same type in the partial %>
  <% # VVV same as the above %>  
  <% #render "comments/comment", collection: @comments %>
  <%= paginate @comments %>
</div>